[package]
name = "example-cairo"
version = "0.1.0"
authors = ["Shotaro Tsuji <Shotaro.Tsuji@gmail.com>"]
edition = "2018"

[dependencies]
cairo-rs = { version = "0.7.0", features = ["pdf"] }
rand = "0.6.5"
